from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor
from reportlab.pdfbase import pdfmetrics

import os


styles = getSampleStyleSheet()

title_style = styles["Heading1"]
title_style.alignment = TA_CENTER
title_style.textColor = HexColor("#1565C0")

heading_style = styles["Heading2"]
heading_style.textColor = HexColor("#1E88E5")

normal_style = styles["BodyText"]


def add_heading(story, text):
    story.append(Paragraph(text, heading_style))
    story.append(Spacer(1, 10))


def add_paragraph(story, text):
    story.append(Paragraph(text, normal_style))
    story.append(Spacer(1, 8))


def generate_pdf_report(
    filename,
    ats_score,
    grade,
    role,
    matched_skills,
    missing_skills,
    strengths,
    suggestions,
    summary,
):
    """
    Generate ATS Resume Analysis Report.
    """

    os.makedirs("reports", exist_ok=True)

    pdf_path = os.path.join("reports", filename)

    doc = SimpleDocTemplate(pdf_path)

    story = []

    # ---------------------------------------------
    # Title
    # ---------------------------------------------

    story.append(
        Paragraph(
            "Resume Job Scanner - ATS Analysis Report",
            title_style,
        )
    )

    story.append(Spacer(1, 20))

    # ---------------------------------------------
    # Overview
    # ---------------------------------------------

    add_heading(story, "Overview")

    add_paragraph(story, f"<b>ATS Score:</b> {ats_score}/100")

    add_paragraph(story, f"<b>Resume Grade:</b> {grade}")

    add_paragraph(story, f"<b>Recommended Job Role:</b> {role}")

    # ---------------------------------------------
    # Summary
    # ---------------------------------------------

    add_heading(story, "Summary")

    add_paragraph(story, summary)

    # ---------------------------------------------
    # Matching Skills
    # ---------------------------------------------

    add_heading(story, "Matched Skills")

    if matched_skills:
        for skill in matched_skills:
            add_paragraph(story, f"• {skill}")

    else:
        add_paragraph(story, "No matching skills detected.")

    # ---------------------------------------------
    # Missing Skills
    # ---------------------------------------------

    add_heading(story, "Missing Skills")

    if missing_skills:
        for skill in missing_skills:
            add_paragraph(story, f"• {skill}")

    else:
        add_paragraph(story, "No missing skills found.")

    # ---------------------------------------------
    # Resume Strengths
    # ---------------------------------------------

    add_heading(story, "Resume Strengths")

    if strengths:
        for item in strengths:
            add_paragraph(story, f"• {item}")

    else:
        add_paragraph(story, "No major strengths identified.")

    # ---------------------------------------------
    # Suggestions
    # ---------------------------------------------

    add_heading(story, "Improvement Suggestions")

    if suggestions:
        for item in suggestions:
            add_paragraph(story, f"• {item}")

    else:
        add_paragraph(story, "Your resume looks good!")

    # ---------------------------------------------
    # Final Verdict
    # ---------------------------------------------

    add_heading(story, "Final Verdict")

    if ats_score >= 80:
        verdict = (
            "Excellent resume. You have a high chance of "
            "passing ATS screening."
        )

    elif ats_score >= 60:
        verdict = (
            "Good resume. Improve a few missing skills "
            "to increase your chances."
        )

    elif ats_score >= 40:
        verdict = (
            "Average resume. Consider adding more relevant "
            "projects and technical skills."
        )

    else:
        verdict = (
            "Your resume needs significant improvements "
            "before applying."
        )

    add_paragraph(story, verdict)

    # ---------------------------------------------
    # Footer
    # ---------------------------------------------

    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            "<b>Generated by Resume Job Scanner V2</b>",
            normal_style,
        )
    )

    doc.build(story)

    return pdf_path
